"use client";

import Link from "next/link";
import { ArrowLeft } from "lucide-react";

const SAMPLE_PROPOSAL = `
PROPOSAL FOR ELECTRICAL SERVICES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

FROM:
Apex Electrical Services LLC
123 Tradesman Blvd, Austin, TX 78701
(512) 234-5678 | info@apexelectrical.com

TO:
Riverside Commercial LLC
pm@riverside.com
(555) 987-6543

Project: 200A Panel Upgrade + EV Charger Install
Address: 4500 Commerce Dr, Austin TX 78701
Date: March 9, 2026
Proposal Valid Until: April 8, 2026

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EXECUTIVE SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Thank you for the opportunity to provide this proposal for the 200A Panel Upgrade + EV Charger 
Installation at 4500 Commerce Dr. Apex Electrical Services specializes in commercial and 
residential electrical services and is committed to delivering quality workmanship, on-time 
completion, and transparent pricing.

We have reviewed the project requirements and are pleased to present this detailed scope of work 
and cost breakdown. Our team holds all required licenses and insurance to perform this work safely 
and in full compliance with local codes.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SCOPE OF WORK
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The following work is included in this proposal:

• 200A Main Breaker Panel (1 ea) — Materials: $650.00 — Labor: $760.00
• 200A Meter Base (1 ea) — Materials: $120.00 — Labor: $190.00
• Level 2 EV Charger (hardwired) (2 ea) — Materials: $900.00 — Labor: $760.00
• 50A Double Pole Breaker (2 ea) — Materials: $50.00 — Labor: $95.00
• Permit & Inspection Fee (1 ea) — Materials: $400.00 — Labor: $380.00

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
INVESTMENT SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  Materials & Equipment:    $2,120.00
  Labor:                    $2,185.00
  ─────────────────────────────────────────────
  Total Investment:         $4,305.00

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TERMS & CONDITIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

• Payment Terms: 50% deposit upon contract signing, 50% upon project completion
• This proposal is valid for 30 days from the date above
• All work performed in accordance with NEC and local electrical codes
• Any changes to scope may affect pricing and schedule
• We carry full general liability and workers' compensation insurance
• All permits required for this work are included in the above pricing

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
WHY APEX ELECTRICAL SERVICES?
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✓ Licensed & Insured — Full coverage for your protection
✓ On-time Completion — We respect your schedule
✓ Clean Jobsite — We clean up every day
✓ Transparent Pricing — No surprise charges
✓ Warranty — 1-year labor warranty on all work performed

We look forward to earning your business. Please don't hesitate to reach out with any questions.

Respectfully submitted,

Apex Electrical Services LLC
(512) 234-5678 | info@apexelectrical.com

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ACCEPTANCE

Client Signature: _________________________________ Date: __________

Printed Name: _____________________________________

Project Address: 4500 Commerce Dr, Austin TX 78701
Total Amount: $4,305.00
`.trim();

export default function DemoPage() {
  return (
    <div className="min-h-screen" style={{ background: '#0a0a0b' }}>
      <div className="max-w-3xl mx-auto px-6 py-12">
        <div className="flex items-center justify-between mb-8">
          <Link href="/" className="flex items-center gap-2 text-zinc-400 hover:text-white transition-colors text-sm">
            <ArrowLeft size={16} /> Back to Home
          </Link>
          <Link href="/signup" className="btn-primary text-sm">
            Create Yours Free →
          </Link>
        </div>

        <div className="text-center mb-8">
          <h1 className="text-3xl font-bold text-white mb-2">Sample BidStack Proposal</h1>
          <p className="text-zinc-500">This is what your clients receive. Generated in under 10 minutes.</p>
        </div>

        <div className="card p-8">
          <div className="flex items-center justify-between mb-6 pb-4" style={{ borderBottom: '1px solid #27272a' }}>
            <div>
              <div className="text-xs text-zinc-500 mb-1">Generated by</div>
              <div className="text-white font-bold">BidStack</div>
            </div>
            <div className="text-right">
              <div className="text-xs text-zinc-500 mb-1">Proposal Value</div>
              <div className="text-2xl font-bold" style={{ color: '#f97316' }}>$4,305</div>
            </div>
          </div>
          <pre className="text-xs text-zinc-300 leading-relaxed whitespace-pre-wrap" style={{ fontFamily: 'monospace' }}>
            {SAMPLE_PROPOSAL}
          </pre>
        </div>

        <div className="text-center mt-8">
          <p className="text-zinc-500 mb-4">Ready to create proposals like this for your jobs?</p>
          <Link href="/signup" className="btn-primary text-base px-8 py-3">
            Start Free Trial — No Card Required
          </Link>
        </div>
      </div>
    </div>
  );
}
